### PR TITLE
Migrate to pyproject.toml and poetry [RHELDST-15226]

### PR DESCRIPTION
**Pull request by negillett**
This commit replaces setup.py and requirements files with pyproject.toml and implements poetry for dependency management in CI.

### CODE REVIEW

**Comment by negillett** [comment]
@release-engineering/ubipop @rbikar ptal

**Comment by rbikar** [comment]
run tests

**Comment by rbikar** [comment]
@negillett 

I guess with this change released we will need to do a slight change in installation procedure, do you think you can look at that as well?
We likely need to change it only in installation in ubipop jobs on jenkins.

**Comment by rbikar** [comment]
seems like integration test failed on installation as well, can you check that as well?
This change cannot be merged without those fixes prepared.

**Comment by negillett** [comment]
@rbikar, yeah, thanks. Looks like poetry just needs to be installed in the installation jobs (including integration test)

**Comment by negillett** [comment]
cc @drepelov, maybe you have some insight on the above question?

**Comment by drepelov** [comment]
> cc @drepelov, maybe you have some insight on the above question?
Well, I would say that in the `ubi-population-jobs.yaml` in `distributon-jenkins-csb` repo,  the installation of poetry should be added just before the ubi-population-tool installation.
For the integration tests, I think it could be enough to just add `pip install poetry` as a first command in `tox.ini` `commands_pre` part.

**Comment by negillett** [comment]
Ah, right, population template is under `chron`.  Thank you, @drepelov.

**Comment by negillett** [comment]
run tests

**Comment by negillett** [comment]
awaiting https://gitlab.cee.redhat.com/exd-guild-distribution/distribution-jenkins-csb/-/merge_requests/415

**Comment by negillett** [comment]
run tests

**Comment by negillett** [comment]
run tests

**Comment by negillett** [comment]
run tests

**Comment by negillett** [comment]
run tests

**Comment by negillett** [comment]
@rbikar, integration tests are failing due to connection error. Should we open a separate ticket to resolve that?

**Comment by negillett** [comment]
@rbikar, @drepelov, I hadn't considered package build and release using poetry but should be addressed now. Dependencies should be locked when installed via pip.

**Comment by negillett** [comment]
I don't expect integration tests to pass, as they haven't been passing for a while now due to connection timeout. Installation in the integration tests, however, is using poetry and is successful.

**Review by rbikar — APPROVED** [review]

**Comment by negillett** [comment]
> @negillett \
> 
> > integration tests are failing due to connection error. Should we open a separate ticket to resolve that?\
> 
> Yes, please open a ticket.

created https://issues.redhat.com/browse/RHELDST-25075

**Pull request merged**
