### PR TITLE
Fix scheme handling and verify option for pulp clients 

### PR DESCRIPTION
**Pull request by rbikar**
In the recent refactoring of pulp clients creation
there were introduced some inconsistent handling of scheme and verify option.

This commit fixes or refactor following:
* fixed scheme handling in pulp_client.py
* naming change: moved from insecure to verify so we don't used double negatives in
  code
* fixed integrations tests after change done in this commit and the
  referenced one

Ref: 7519ee3c8c79691bf2612a3b5d4b8756bd05458d

### CODE REVIEW

**Comment by rbikar** [comment]
run tests

**Comment by rbikar** [comment]
run tests

**Comment by rbikar** [comment]
run tests

**Comment by rbikar** [comment]
run tests

**Comment by rbikar** [comment]
run tests

**Review by rohanpm — APPROVED** [review]

**Pull request merged**
