### PR TITLE
clean-up: remove dead code, format touched files [RHELDST-141]

### PR DESCRIPTION
**Pull request by negillett**

### CODE REVIEW

**Comment by negillett** [comment]
Had to add a couple tests to cover what was touched

**Comment by negillett** [comment]
Idk what's going on with this Jenkins CI check, not seeing any movement on Jenkins itself nor any way to trigger it here (no access to settings).

**Comment by rbikar** [comment]
@negillett 
On the first sight I was a bit worried if the code you removed is really dead, but it seems like there you're right and for some reason we kept a lot of dead code during latest development. 

Will try to running integration tests via Jenkins, but currently it is not really reliable.

**Comment by rbikar** [comment]
run tests

**Review by rbikar — APPROVED** [review]

**Comment by rbikar** [comment]
run tests

**Pull request merged**
